server:
  port: 28080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
#  数据库连接，还没有建立数据库
  datasource:
    url: jdbc:mysql://39.101.65.178:3306/clap
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
